setwd("D:\\paper\\\data\\macro uncertainty")
# install.packages("fGarch")
# install.packages("FinTS")
# install.packages("rJava")
# install.packages("xlsx")
#install.packages("JDK")

library(FinTS)
library(fGarch)
library(timeSeries)
library(xlsx)
library(quantmod)
realgdp_season<-read.xlsx("D:\\paper\\data\\macro uncertainty\\exchangeratedollar.xls", sheetIndex=1,startRow = 3, endRow = 178)
#View(gdp_season)
#head(gdp_season)
#tail(gdp_season)
#dim(gdp_season)
#str(gdp_season)
gdp <- xts(realgdp_season[,-1], order.by=realgdp_season[,1])
#str(gdp)
#View(gdp)
#gdp<-as.xts(gdp_season)

#View(ptm.gdp)
#ptm.gdp<-diff(gdp)
#ptm.gdp<-ptm.gdp[-1,]
#plot(ptm.cpi)
#head(ptm.cpi)

#index(gdp)
#substr(index(gdp),4,8)
Box.test(gdp,lag=12,type = 'Ljung-Box')
Box.test(gdp^2,lag=12,type = 'Ljung-Box')

library(FinTS)
ArchTest(x=gdp,lags=12)

epst<-gdp-mean(gdp)
par(mfrow=c(1,2))
acf(as.numeric(epst)^2,lag.max = 20,main="squared series")
pacf(as.numeric(epst)^2,lag.max = 20,main="squared series")

library(fGarch)
GARCH.model_1<-garchFit(~garch(1,1),data=gdp,trace=FALSE)
summary(GARCH.model_1)


vol_1<-fBasics::volatility(GARCH.model_1)
#View(vol_1)
sres_1<-residuals(GARCH.model_1,standardize=TRUE)

vol_1.ts<-ts(vol_1,frequency = 12,start = c(2002,1))
vol.ts<-as.timeSeries(vol_1.ts)
sres_1.ts<-ts(sres_1,frequency = 12, start = c(2002,1))
sres.ts<-as.timeSeries(sres_1.ts)
plot(vol_1.ts,xlab='year',ylab='volatility')
plot(sres_1.ts,xlab='year',ylab='sd')

par(mfrow=c(2,2))
acf(sres_1,lag=24)
pacf(sres_1,lag=24)
acf(sres_1^2,lag=24)
pacf(sres_1^2,lag=24)
par(mfrow=c(1,1))
qqnorm(sres_1)
qqline(sres_1)

vol_out<-as.data.frame(vol.ts)
#sres_out<-as.timeSeries(sres.ts)
#View(vol_out)
#str(vol_out)
#WriteXLS(vol_out, "D:\\paper\\output\\uncertainty\\M2.xlsx",SheetNames="vol")
write.xlsx(vol_out, "D:\\paper\\output\\uncertainty\\exchangeratedollar.xlsx",sheetName = "exchangeratedollar voltality monthly")
#View(vol_out[,1])
vol_out_tmp<-t(as.matrix(vol_out[c(1:315),1]))

#View(vol_out_tmp)
vol_season<-matrix(vol_out_tmp,ncol  = 3,byrow = TRUE)
#View(vol_season)
vol_season_mean<-rowMeans(vol_season)
#View(vol_season_mean)
#str(vol_season_mean)
#seriesData(vol_1.ts)
#is.timeSeries(vol.ts)
#cpi_date<-seq(as.Date("1990-03-31"), as.Date("2016-03-31"), by = "3 months")
#cpi_date<-t(cpi_date)
#View(cpi_date)
#cpi_vol<-c(cpi_date,vol_season_mean)
vol_season.ts<-ts(vol_season_mean,frequency = 4,start = c(2002,1))
#str(vol_season.ts)
#View(vol_season.ts)
vol_season.ts<-as.timeSeries(vol_season.ts)
#View(vol_season.ts)
write.xlsx(vol_season.ts, "D:\\paper\\output\\uncertainty\\exchangeratedollar.xlsx",sheetName = "exchangeratedollar voltality seasonly",append=TRUE)
plot(vol_season.ts)