library(FinTS)
library(xlsx)
#library(quantmod)
library(fGarch)
library(timeSeries)
setwd("C:\\UM\\calGARCH\\macro uncertainty 2nd")

cpi_month<-read.xlsx2("C:\\UM\\R\\calGARCH\\data\\macro uncertainty 2nd\\CPI monthly 90.01-16.06.xls", sheetIndex=1,startRow = 2)
View(cpi_month)
cpi <- xts(cpi_month[,2], order.by=cpi_month[,1])
ptm.cpi<-diff(cpi)
ptm.cpi<-ptm.cpi[-1,]
Box.test(ptm.cpi,lag=12,type = 'Ljung-Box')
ArchTest(x=ptm.cpi,lags=12)
epst.cpi<-ptm.cpi-mean(ptm.cpi)
acf(as.numeric(epst.cpi)^2,lag.max = 20,main="squared series")
pacf(as.numeric(epst.cpi)^2,lag.max = 20,main="squared series")
GARCH.model_cpi<-garchFit(~garch(1,1),data=ptm.cpi,trace=FALSE)
summary(GARCH.model_cpi)
vol_1<-fBasics::volatility(GARCH.model_cpi)
vol_1.ts<-ts(vol_1,frequency = 12,start = c(1990,1))
vol.ts<-as.timeSeries(vol_1.ts)
vol_out<-as.data.frame(vol.ts)
write.xlsx2(vol_out, "C:\\UM\\calGARCH\\output\\cpi.xlsx",sheetName = "CPI voltality monthly")

vol_out_tmp<-t(as.matrix(vol_out[c(1:315),1]))
vol_season<-matrix(vol_out_tmp,ncol  = 3,byrow = TRUE)
#View(vol_season)
vol_season_mean<-rowMeans(vol_season)
vol_season.ts<-ts(vol_season_mean,frequency = 4,end = c(2016,2))
vol_season.ts<-as.timeSeries(vol_season.ts)
write.xlsx(vol_season.ts, "C:\\UM\\calGARCH\\output\\cpi.xlsx",sheetName = "CPI voltality seasonly",append=TRUE)
plot(vol_season.ts)